[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
truncation_length = 2
fish_style_pwd_dir_length = 1


[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[custom.fish_private]
when = 'test  "$STARSHIP_SHELL" = "fish" -a -n "$FISH_PRIVATE_MODE"'
shell = ['sh', '--norc']
description = "Indicates that fish shell is in private mode"
symbol = "﫸 "
style = "purple"

[custom.kakoune]
symbol = '🐈'
command = 'kcr prompt'
when = 'kcr prompt'
shell = ['sh']
description = 'The current Kakoune session and client'
style = 'green'
format = '[$symbol $output]($style)'
