[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
truncation_length = 2
fish_style_pwd_dir_length = 1


[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[custom.fish_private]
when = 'test  "$STARSHIP_SHELL" = "fish" -a -n "$FISH_PRIVATE_MODE"'
shell = ['sh', '--norc']
description = "Indicates that fish shell is in private mode"
symbol = "﫸 "
style = "purple"

[custom.kakoune_connect_client]
symbol = '🐈'
command = 'printf "${KAKOUNE_CLIENT}@${KAKOUNE_SESSION}"'
when = 'test "$IN_KAKOUNE_CONNECT" = 1 -a -n "$KAKOUNE_SESSION" -a -n "$KAKOUNE_CLIENT"'
shell = ['sh', '--norc']
description = 'Indicates that the current shell is connected to a Kakoune client'
style = 'green italic'
format = '[$symbol ($output )]($style)'

[custom.kakoune_connect_session]
symbol = '🐈'
command = 'printf "${KAKOUNE_SESSION}"'
when = 'test "$IN_KAKOUNE_CONNECT" = 1 -a -n "$KAKOUNE_SESSION" -a -z "$KAKOUNE_CLIENT"'
shell = ['sh', '--norc']
description = 'Indicates that the current shell is connected to a Kakoune session'
style = 'green italic'
format = '[$symbol ($output )]($style)'
